name: sample ci pipeline

on:
  push:
    branches:
      - master
      - develop
      #- feature/one
  workflow_dispatch:

env:
  IMAGE_NAME: ${{vars.image_name}}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with: 
          node-version: ${{vars.node_version}}
          cache: npm
      
      - name: install dependencies
        run: npm ci

      - name: test
        run: npm test
      
      - name: build the app
        run: npm run build
      
      - name: build echo
        run: echo " building the app"

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-dist
          path: dist/

      

  containerize:
    #if: ${{ vars.ENABLE_CONTAINER == true }}
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: code checkout
        uses: actions/checkout@v4

      - name: download artifact
        uses: actions/download-artifact@v4
        with: 
          name: app-dist
          path: dist/

      - name: docker build
        run: |
          docker build -t ${{env.IMAGE_NAME}}:${{github.sha}} .

      - name: docker images list
        run: docker images

      - name: docker login
        run: |
          echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin

      - name: docker push
        run: docker push ${{env.IMAGE_NAME}}:${{github.sha}}